### ISSUE TITLE
1時間当たりの居住人数がp人における局所換気設備の消費電力量

### ISSUE THREAD

**Issue by HisashiMiura** [SMizutani/Ventilation#4]
「1時間当たりの居住人数がp人における局所換気設備の消費電力量」を記述してください。

それには、365日分の「平日」「休日在宅」「休日外出」のスケジュールリストが必要かもしれません。

**Comment by SMizutani** [comment]
記述してみました。
ご確認お願いいたします。

**Comment by HisashiMiura** [comment]
E_E_VL_p を計算する関数が必要ではありませんか？

**Comment by SMizutani** [comment]
すいません、理解できていないのですが、年間消費量を算出するための関数ということでしょうか？？

**Comment by HisashiMiura** [comment]
違います。局所換気設備のWhを求める再に、任意の日付と任意の人数(1,2,3,4)を入力すると、Whを出力として出す関数です。
E_E_VL_p(day,person)
みたいなかんじです。

**Comment by SMizutani** [comment]
イメージわいてきました。
E_E_VL_p(day,person)から出力するのは日合計ですか。
それとも時刻も指定して出力させますか。

**Comment by HisashiMiura** [comment]
ごめんなさい。換気の場合は１時間単位でしたから、
E_E_VL_p(day,hour,person)
でしたね。

**Comment by SMizutani** [comment]
承知しました。考えてみます。
今のところ3次元データベースを構築し、そこからデータ抽出の関数を作るイメージが浮かんでいます。

**Comment by SMizutani** [comment]
修正してみましたがいかがでしょうか。
ご確認お願いいたします。

**Comment by SMizutani** [comment]
pandasを用いない方法に修正してみました。
いかがでしょうか。

**Comment by HisashiMiura** [comment]
確認しました！
OKです。
